services:
  jekyll:
    image: ruby:3.3
    container_name: blog
    working_dir: /srv/jekyll
    command: bash -c "gem install bundler && bundle install && bundle exec jekyll serve --host 0.0.0.0 --force_polling --livereload"
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - ./:/srv/jekyll
      - jekyll_bundle:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
      - BUNDLE_PATH=/usr/local/bundle
    restart: unless-stopped

volumes:
  jekyll_bundle:
    driver: local